[Network]
Type="channel"
CAFile="./configs/sdk_cert/ca.crt"
Cert="./configs/sdk_cert/sdk.crt"
Key="./configs/sdk_cert/sdk.key"

[[Network.Connection]]
NodeURL="10.20.3.2:20200"
GroupID=1

[Account]
KeyFile="./configs/sdk_cert/0x.pem"

[Chain]
ChainID=1
SMCrypto=false

[Log]
Path="./"
Level="debug"